### ISSUE TITLE
bug: Extension context invalidated.

### ISSUE THREAD

**Issue by ZerGo0** [ZerGo0/Ftv-extension#19]
https://wxt.dev/guide/essentials/content-scripts.html#context

```
Uncaught (in promise) Error: Extension context invalidated.
    at en (home.js:2:1706)
    at Zt (home.js:1:15015)
    at lr (home.js:2:21812)
```

**Comment by ZerGo0** [comment]
Pretty hard to reliably reproduce, closing this for now.
